### ISSUE TITLE
RADEX One Serial Not found

### ISSUE THREAD

**Issue by mlewis3141** [luigifab/python-radexreader#14]
Hello

I was trying to use this tool to read data from the Radex one on Ubuntu 18.04.  When I run the code I get the following

![image](https://github.com/luigifab/python-radexreader/assets/135241436/effb9afc-a9a8-4605-9336-16d627fe551a)

I ran the lsusb command and the Radex device is the device 10.  I looked briefly at the code, and it looks like it is looking for the abba:a011 device.  I am not a computer programmer, but am only looking to get this working.  

Let me know if you have any suggestions.  

Thanks

**Comment by luigifab** [comment]
Can you try [this version](https://gist.github.com/luigifab/c3709a860754e3e67c8a2977b5ddfbea) (you must replace the file).
Since 1.2.1 I made some changes.

**Comment by luigifab** [comment]
Perhaps fixed in v1.2.2.

**Comment by mlewis3141** [comment]
Hello

I tried that, but did not work for me.

Thanks
Monte

**Comment by mlewis3141** [comment]
Hello

I saw you released the new version, which I will try.

Thanks
Monte

**Comment by luigifab** [comment]
Today, I have an idea!

Based on your screenshot, my program detect your abba:a011 device, but crash after.
I think this is because your device name seems to be empty, and the program search RADEX.

Can you try to create the following file a.py with:

```py
# https://stackoverflow.com/a/25112066/2980105
import serial.tools.list_ports
ports = list(serial.tools.list_ports.comports())
for p in ports:
  print(p)
```

Then run `python3 a.py` to see results.

**Comment by Tobbinloggin** [comment]
Long time no see! I'm back. I took a break from this project but upon my return it appears our gist for the Radex One has been deleted. I downloaded the newest version of the project to play around with and it appears I can't read information from it and it does not work anymore, I'm getting this not found error with my device!
```
/app/src/src # nano a.py # Created the a.py script you wrote
/app/src/src # python3 a.py
# no output
/app/src/src # python3 radexreader-cli.py tail

 radexreader-local 1.2.5 − python 3.12.9, pyusb 1.3.1, pyserial 3.5
Traceback (most recent call last):
  File "/app/src/src/radexreader-cli.py", line 56, in <module>
    reader = radexreader.RadexReader()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/src/radexreader/__init__.py", line 68, in __init__
    raise ValueError('Error: RADEX ONE (serial) not found')
ValueError: Error: RADEX ONE (serial) not found
/app/src/src #
```
This is all being ran within a docker container.
```
# Base image with Python 3.12 and Alpine
FROM python:3.12-alpine

# Install required packages
RUN apk add --no-cache libusb git \
    # Install distutils for Python package compilation
    && apk add --no-cache python3-dev build-base

# Install Python dependencies
RUN python3 -m pip install --no-cache-dir pyusb pyserial radexreader setuptools

# Clone the repository and copy the 'src' folder
RUN git clone https://github.com/luigifab/python-radexreader.git /tmp/python-radexreader \
    && mkdir -p /app/src \
    && cp -r /tmp/python-radexreader/src /app/src \
    && rm -rf /tmp/python-radexreader

# Make everything in the /app/src folder executable
RUN chmod -R +x /app/src/*

# Set working directory for convenience
WORKDIR /app/src

# Default command (optional, for ease of use)
CMD ["/bin/sh"]
```
Use the Dockerfile to recreate my environment. (Yeah, I know some of it is unnecessary, I was trying to fix the issue myself so I added some extra unneeded packages)
```
/app/src/src # lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux 6.1.21+ dwc_otg_hcd DWC OTG Controller
Bus 001 Device 004: ID abba:a011 Silicon Labs RADEX ONE
Bus 001 Device 003: ID 0424:ec00
Bus 001 Device 002: ID 0424:9512
```

lsusb does list the RADEX ONE as a device within the docker container.

**Comment by luigifab** [comment]
Alright.

When I test my program with Alpine (with Radex RD1212), I do:
```bash
sudo docker run --rm --user root -it --privileged -v /var/www:/var/www -v /dev:/dev python:3.13-alpine /bin/sh

apk update ; apk add libusb ; python3 -m pip --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org install pyusb pyserial ; python3 /var/www/cool/code/python-radexreader/src/radexreader-cli.py tail
```

Anyway, for you, the program stop here:
https://github.com/luigifab/python-radexreader/blob/b63c42dde5504536ba44952d8450b897b3fc6e21/src/radexreader/__init__.py#L59-L68

So USB device is found, and serial device isn't.
The idea of a.py, is to list "available" devices, but if there are no results...
From [documentation of pyserial](https://pyserial.readthedocs.io/en/latest/shortintro.html#listing-ports), you can also try: `python3 -m serial.tools.list_ports -v -s`

**Comment by luigifab** [comment]
I also forgot issue #17, does it help?

**Comment by Tobbinloggin** [comment]
Here are the results:
```
/app/src # python3 -m serial.tools.list_ports -v -s
no ports found
```
I tried the modprobe command and it said `/lib/modules` does not exist.

**Comment by luigifab** [comment]
what is the result of dmesg before/after modprobe?

**Comment by Tobbinloggin** [comment]
```
/app/src # lsusb -d abba:a011
Bus 001 Device 001: ID 1d6b:0002 Linux 6.1.21+ dwc_otg_hcd DWC OTG Controller
Bus 001 Device 004: ID abba:a011 Silicon Labs RADEX ONE
Bus 001 Device 003: ID 0424:ec00
Bus 001 Device 002: ID 0424:9512
/app/src # echo abba a011 >/sys/bus/usb-serial/drivers/cp210x/new_id
/bin/sh: can't create /sys/bus/usb-serial/drivers/cp210x/new_id: nonexistent directory
/app/src #
/app/src # python3 src/radexreader-cli.py tail

 radexreader-local 1.2.5 − python 3.12.9, pyusb 1.3.1, pyserial 3.5
Traceback (most recent call last):
  File "/app/src/src/radexreader-cli.py", line 56, in <module>
    reader = radexreader.RadexReader()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/src/radexreader/__init__.py", line 68, in __init__
    raise ValueError('Error: RADEX ONE (serial) not found')
ValueError: Error: RADEX ONE (serial) not found
/app/src # dmesg | tail -n 20
[    5.305156] systemd[1]: System time before build time, advancing clock.
[    5.320563] usb 1-1.3: new full-speed USB device number 4 using dwc_otg
[    5.456348] usb 1-1.3: New USB device found, idVendor=abba, idProduct=a011, bcdDevice= 1.00
[    5.456408] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    5.456428] usb 1-1.3: Product: RADEX ONE
[    5.456444] usb 1-1.3: Manufacturer: Silicon Labs
[    5.456459] usb 1-1.3: SerialNumber: 0001
. . .
[ 1862.392237] docker0: port 1(veth2a877e9) entered forwarding state
[ 1864.189951] docker0: port 1(veth2a877e9) entered disabled state
[ 1864.194333] vethd1bb757: renamed from eth0
[ 1864.294813] docker0: port 1(veth2a877e9) entered disabled state
[ 1864.296595] device veth2a877e9 left promiscuous mode
[ 1864.296645] docker0: port 1(veth2a877e9) entered disabled state
[33763.836411] docker0: port 1(vethdfb6850) entered blocking state
[33763.836466] docker0: port 1(vethdfb6850) entered disabled state
[33763.836973] device vethdfb6850 entered promiscuous mode
[33766.596349] eth0: renamed from veth664b39d
[33766.712449] IPv6: ADDRCONF(NETDEV_CHANGE): vethdfb6850: link becomes ready
[33766.712746] docker0: port 1(vethdfb6850) entered blocking state
[33766.712783] docker0: port 1(vethdfb6850) entered forwarding state
[77148.454116] docker0: port 2(veth54ae2d3) entered blocking state
[77148.454174] docker0: port 2(veth54ae2d3) entered disabled state
[77148.454684] device veth54ae2d3 entered promiscuous mode
[77151.279035] eth0: renamed from vethf13f194
[77151.378482] IPv6: ADDRCONF(NETDEV_CHANGE): veth54ae2d3: link becomes ready
[77151.378779] docker0: port 2(veth54ae2d3) entered blocking state
[77151.378816] docker0: port 2(veth54ae2d3) entered forwarding state
```

**Comment by luigifab** [comment]
try again as root but outside docker?
```
# connect the device
dmesg | tail -n 20
modprobe cp210x
echo abba a011 >/sys/bus/usb-serial/drivers/cp210x/new_id
dmesg | tail -n 20
# registered new interface driver ?
# if not, unplug and plug again the device
```

**Comment by Tobbinloggin** [comment]
```
root@Lalande:~# modprobe cp210x
root@Lalande:~# echo abba a011 >/sys/bus/usb-serial/drivers/cp210x/new_id
root@Lalande:~# dmesg
[    5.320563] usb 1-1.3: new full-speed USB device number 4 using dwc_otg
[    5.456348] usb 1-1.3: New USB device found, idVendor=abba, idProduct=a011, bcdDevice= 1.00
[    5.456408] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    5.456428] usb 1-1.3: Product: RADEX ONE
[    5.456444] usb 1-1.3: Manufacturer: Silicon Labs
[    5.456459] usb 1-1.3: SerialNumber: 0001
. . .
[23920.802402] usbcore: registered new interface driver usbserial_generic
[23920.802560] usbserial: USB Serial support registered for generic
[23920.834597] usbcore: registered new interface driver cp210x
[23920.834755] usbserial: USB Serial support registered for cp210x
[23942.293740] cp210x 1-1.3:1.0: cp210x converter detected
[23942.307929] usb 1-1.3: cp210x converter now attached to ttyUSB0
root@Lalande:~# python3 -m serial.tools.list_ports -v -s
/dev/ttyUSB0
    desc: RADEX ONE - RADEX ONE
    hwid: USB VID:PID=ABBA:A011 SER=0001 LOCATION=1-1.3
1 ports found
root@Lalande:~# sudo docker run --rm --user root -it --privileged -v /dev:/dev with-src /bin/sh
/app/src # python3 -m serial.tools.list_ports -v -s
/dev/ttyUSB0
    desc: RADEX ONE - RADEX ONE
    hwid: USB VID:PID=ABBA:A011 SER=0001 LOCATION=1-1.3
1 ports found
/app/src # python3 src/radexreader-cli.py tail

 radexreader-local 1.2.5 − python 3.12.9, pyusb 1.3.1, pyserial 3.5
 manufacturer  0xabba  Silicon Labs
 product       0xa011  RADEX ONE
 comport       /dev/ttyUSB0

[info] Sensor: Geiger-Müller tube SBM 20-1
[info] Measuring range: 0.05 - 999 µSv/h
[info] Uncertainty of the result: ±(15+6/D)%
[info]   D is the value after a complete cycle of 100? seconds

[warn] The values shown are only approximations.
[warn] The actual value can only be measured with suitable professional device.
[warn] For now, not tested with measured values greater than 0.25 µSv/h.

2025-03-21 12:20:55+00:00    0.18 µSv/h  ±48% (0.09 ≤ 0.18 ≤ 0.27)
                       5.95 µSv accumulated /     29 CPM  [±48%]
2025-03-21 12:21:05+00:00    0.18 µSv/h  ±48% (0.09 ≤ 0.18 ≤ 0.27)
                       5.95 µSv accumulated /     28 CPM  [±48%]
```
Running the commands _outside of the docker_ fixed the issue completely!

**Comment by luigifab** [comment]
beautiful, so I have to add this to the readme

**Comment by luigifab** [comment]
is it persistent after a reboot?
anyway, with packages I think I need to do this (with right ids): https://unix.stackexchange.com/a/165845/364800

so for **/usr/lib/udev/rules.d/60-python3-radexreader.rules** I think:
```
SUBSYSTEM=="usb", ATTR{idVendor}=="03eb", ATTR{idProduct}=="5603", TAG+="uaccess"
SUBSYSTEM=="usb", ATTR{idVendor}=="10c4", ATTR{idProduct}=="ea60", TAG+="uaccess"
SUBSYSTEM=="usb", ATTR{idVendor}=="abba", ATTR{idProduct}=="a011", TAG+="uaccess", RUN+="/sbin/modprobe cp210x" RUN+="/bin/sh -c 'echo abba a011 > /sys/bus/usb-serial/drivers/cp210x/new_id'"
```

**Comment by luigifab** [comment]
Sounds good, udev and readme updated for next release.
